irislib/iris-messenger

README.md
The current URL doesn't work if you don't have an SSH key uploaded to Github (as I just discovered cloning this onto a new machine). The https URL should work for more people.
=> Change git clone URL to https

README.md, package.json
- Default port of http-server is 8080, updating in README.
- Run http-server with npx so you don't need it installed globally.
=> Fix port, run server with npx

src/css/style.css, src/js/Translations.js, src/js/views/Contacts.js
Before, when you have no contacts in your list, the Contacts page
is empty with some dangling lodash on the screen making it look broken.
Moving forward, it will display a meaningful message for the user.
=> Add meaningful UI for empty contact list

src/css/style.css
This way, the items will have a bit of room so the ADD TO CART
button doesn't wrap anymore.
=> Add minimum width to store items

README.md, src/js/views/About.js
The disclaimer about iris-messenger not being ready for security-critical purposes is the most important part of the Privacy section. This change moves it to the top of the section.
=> docs: do not bury the lede in the Privacy section

src/css/style.css, src/js/components/PublicMessage.js, src/js/views/Notifications.js
I think that the quoted message UI can be improved a bit. For me is not always easy to pick up the main message against the quoted one. Proposal:
* Lower the contrast prominence of the quoted message
* Fix the vertical alignment
Actual rendering:
Proposed:
PS: I took the chance to reset the sender name font size because the profile image anyway takes some space, is not useful to reduce the text size.
=> Improve the quoted message UI and new / reply message form

src/js/components/FeedMessageForm.js, src/js/components/PublicMessage.js, src/js/views/Message.js
Little touches to improve the UX on mobile on posting a new note:
* Add a caption to the send button for new posts on mobile, missing file from pull request #176: the mobile button is ok full screen for usability, let's add some text make it clear what it does.
@mmalmi perhaps could be better to add a new text/translation "Post public note" instead of "Send message"?
* Fix the autofocus for new post form on mobile: on mobile when the user click the (+) icon the text area is the only and main element, so is ok to focus it and open the keyboard.
PS: My React skills are zero, so feel free to tweak the code!
PPS: This a duplicate of the closed [#178](https://github.com/irislib/iris-messenger/pull/178).
=> Improve new post UX on mobile

src/css/style.css
=> Remove the useless space on the right of the quoted message

src/template.html
Hi, just stumbled upon this.
This change allows scalable two finger pinch zoom on mobile,
there are a lot of good graphical content with high res and detail. but iris was not able on
mobile to zoom in.
I tested this patch with a local clone on a Tor instance over torbrowser and on firefox and chrome , and all click buttons, and functions worked so far, even when zoomed.
The whole app feel is now way more *mobile* feel, and all your magic work like charm
=> make iris pinch scalable on mobile

src/js/components/PublicMessage.js
Empty kind 6 events were a wrong NIP, no one implements them.
https://github.com/nostr-protocol/nips/blob/master/10.md has a safer way to "retweet" that most clients implement.
=> Stop sending empty kind:6 events. use kind:1 with a reference instead.

src/js/Nostr.ts
nostr.bitcoiner.social -> offchain.pub
note1zpgy9f8tlwdwhhwtzy50vpl72qkunzhmy57p4f5xaf8h57pfvwpschwe74
> Before I deployed the new pay-to-relay server, I ran a public relay under a "nostr" subdomain. I've since renamed my public relay to wss://offchain.pub. Much cooler name. Better represents how nostr isn't something this domain handles on the side, it's the primary purpose. Raison d'etre.
> 
> Both offchain.pub and the "nostr" subdomain will work concurrently for awhile, pointing to the same public relay server. But I'll eventually deprecate the "nostr" subdomain and redirect requests to the new offchain.pub name.
=> Public relay name change

src/js/Nostr.ts
The subscription to `everything new` was lost for some reason.
Sometimes it worked when multiple relays are configured, but when only one relay is used new events are not handled (although the relay sends them correctly)
The solution follows the  `our stuff` and `notifications and DMs` approach and delays the subscription.
=> fix: subscription to `new`

src/js/Helpers.tsx, src/js/components/MessageForm.js
Hello, iris!
To implove searchability of message, I want to set [t(topic)-tag](https://github.com/nostr-protocol/nips/blob/master/12.md#suggested-use-cases) in message when send it.
So, I changed message sending process to extract `#`-prefixed format string(e.g. `#hashtagOrTopic`) in content and set it as t-tag.
Please review at your convenience.
=> Set t-tag when send message

src/js/components/SafeImg.tsx
fixed that l.53 in 9072d0d3142039e01f858b3e9e6420da6112b890 broke [`openAttachmentsGallery()` calling](https://github.com/irislib/iris-messenger/blob/47ea993daa4f0456dc9935b38ff5adce97b3cf13/src/js/components/PublicMessage.js#L708)
=> add onClick prop to SafeImg explicitly

src/js/components/Identicon.tsx, src/js/components/SafeImg.tsx
profiles like this one with a large profile picture, show a large oval instead of the regular circle pfp: https://iris.to/npub1y73qksdxdv6ags3s9fgv5xa26ukzakzyergjynyld4g2zf6jpp8q45htck
the problem was ` style={{ width: width, height: width }}` is an invalid value, since the correct is using the `px` suffix `style={{ width: '${width}px', height: '${width}px' }}`, also there's no point declaring the `<SafeImg>` component at the middle of render, also added `style={{ objectFit: 'contain' }}` to make the full large picture fit inside the smaller size
=> fix: wrongly shaped identicons

src/js/Helpers.tsx
Fixes #286 
All bech32 prefixes end in a `1` so by including the `1` in the regex we can differentiate real LNURLs from mentions of the word LNURL.
=> Improved lightning link regex

src/js/views/settings/NetworkSettings.jsx
Title says it all. Trying to scratch my own itch here, since I often forget the "wss://".
Kept PR as small as possible. Other cleaning of the relay URL would also be thinkable here, e.g. trim, remove trailing slash, etc..
Please advise if you think it is useful at all and whether you would like me to implement it differently.
=> ensure relay URL includes a protocol ("://"), else prefix wss://

src/js/components/PublicMessage.js
I don't make sure why this happended but probably zap notification could have tags that does not have e tag.
```
Uncaught TypeError: Cannot read properties of undefined (reading '1')
at ge.renderZap (PublicMessage.js:419:72)
at ge.render (PublicMessage.js:610:21)
at _ (index.js:192:13)
at component.js:132:3
at Array.some (<anonymous>)
at d (component.js:211:9)
```
=> e tag for zap could be undefined

src/js/Helpers.tsx, src/js/views/settings/Media.js
This PR enables Wavlake track/album/artist links shared in Nostr notes to be rendered as a custom embedded player (see example screenshot). The player also supports boosting via invoices. The iframe has been defined with the minimum number of attributes needed -- wasn't sure if some of the others are preferred for iris but I thought I'd err on the minimal side for now.
Please let me know if you need any changes. Would love to see these shared links work on iris.
=> Add Wavlake embedded player

src/js/Helpers.tsx
We just updated our site so that the music player lives on wavlake.com. This update allows Iris to render embeds correctly for tracks/albums/artists from both the legacy player.wavlake.com links as well as the new ones.
=> Wavlake: Update regex to support home domain links

Dockerfile
This PR updates the Dockerfile to use a multi-stage build to reduce the final image size, while also making subsequent builds faster by caching dependencies.
I have tested this Dockerfile on the `production` branch as of commit `a2de27cd`.  
Image here under `production-test` tag: https://hub.docker.com/repository/docker/nmfretz/iris-messenger/tags?page=1&ordering=last_updated
=> update dockerfile to use multi-stage build

.github/workflows/on-tag.yml
This PR adds a GitHub Actions workflow to automatically build and push multi-arch (amd64 & arm64) Docker images to a Docker registry when a new git tag is pushed that matches the [Semantic Versioning](https://semver.org/) pattern. 
For example, this will build/push images when tags like `0.5.0`, `v0.6.1`, `0.2.1-beta`, etc are [pushed](https://stackoverflow.com/a/18223354). Two multi-arch images will be pushed to the Docker repository:
1) An image with a tag that is the same as the recently-pushed git tag (e.g., `irislib/iris-messenger:v1.0.0`)
2) An image with the `latest` tag (e.g., `irislib/iris-messenger:latest`)
Here are the GitHub secrets needed for this workflow (for the Docker registry credentials): https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encry …
=> add workflow to build and push docker image on tag

package.json
When testing on a machine which already has something else running on port 8080, I got the following behavior when trying to manually set the port:
```
yarn serve --port=8085 --host 0.0.0.0
...
Your application is ready~! 🚀
➡ Port 8080,8085 is taken; using 37543 instead
- Local:      http://0.0.0.0:37543
- Network:    http://192.168.2.2:37543
────────────────── LOGS ──────────────────
```
It doesn't matter what port I pick.
This PR drops 8080 from package.json which makes the above issue go away. By default it still picks port 8080.
=> Don't hardcode port 8080 in package.json

src/js/Helpers.tsx
Not all international hashtags are rendering properly on Iris today (Both in profile description and also in note content).
Visit the profile with NIP-05 ID - vivganes@vivekganesan.com
Visit the note at URL - https://iris.to/note1lzeujaaaqlqju6vdg7su3w73h5uv2v4zw65rxlgjccwdm6wq9qusfh8czp 
Note that intl hashtags are not rendered.
It is due to regex looking for only english chars, numbers and _
Use a blacklist instead of whitelist to look for hashtags (much like the solution here: https://stackoverflow.com/a/27343333)
Similar PRs have been accepted in other clients (snort and amethyst)
=> Support international hashtags

src/js/components/feed/BaseFeed.tsx
HJKL keys can be used for scrolling on certain social networks like Facebook, Twitter, or 9GAG, providing a quick way to navigate through feeds or timelines. Over time, the HJKL keys found their way into other applications and environments, particularly those that aimed to provide Vim-like keybindings or cater to Vim users. This includes various text editors, command-line interfaces, and even certain web-based applications.
I implemented simple scrolling with J and K keys for iris
=> Added ability to scroll feed with J and K keys

src/js/views/settings/Network.tsx
This was just bugging me a bit. Happy for any feedback.
- because of one long relay-url the buttons are being pushed out of the visible screen on small screens
- "network"-list entries are now being truncated ("popular"-list entries are being truncated)
- add truncate to "network"-entries as well
- add maximum-width to relay-urls
=> Fix: make network relay usable on mobile

src/js/components/modal/Zap.tsx
Move close button to top right of zap modal.
After fixed:
=> fix: move close button to top right of modal

src/js/components/modal/Zap.tsx
We had a bug when trying to parse the json of a comment. It had a `\n` at the end of it and our browser's json parser couldn't handle it. This should fix
=> Trim Zap comment
